version: 2
updates: 
  - package-ecosystem: "docker"
    directory: "/tile-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tile-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
