name: Build and deploy services

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        service:
          - tile-service
          - segment-service

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch,enable=true
            type=ref,event=tag,enable=true
            type=raw,value=latest,enable={{ is_default_branch }}
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ github.repository }}/${{ matrix.service }}:latest
          cache-to: type=inline
