name: Cleanup container registry

on:
  workflow_dispatch:

jobs:
  cleanup:
    strategy:
      matrix:
        service:
          - tile-service
          - segment-service

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove untagged container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: segment-aerial-images/{{ matrix.service }}
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0
