name: Build tile service

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      
      - name: Install dependencies
        run: npm ci
        working-directory: tile-service
